# Generated by Django 3.2.16 on 2022-11-30 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description_question',
            field=models.CharField(max_length=50, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Разрешается использовать только кириллицу', regex='^[А-Яа-я -]*$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Разрешается использовать только кириллицу', regex='^[А-Яа-я -]*$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Разрешается использовать только латиницу', regex='^[A-Za-z -]*$')], verbose_name='Логин'),
        ),
    ]
