# Generated by Django 3.2.16 on 2022-11-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20221130_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='all_votes',
            field=models.IntegerField(default=0),
        ),
    ]
